In [ ]:
#THIS IS ALL ABOUT DATAFRAMES

In [ ]:
#PANDA SERIES
# a series is a 1d array which hold any data type. The axis labels are collectively called the index

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([15,16,17])
dic = {1:10,2:20,3:30}

In [ ]:
pd.Series(my_list) #here indexes are called as labels

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list,index=labels) # here we have put labels as indexes which we have created

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr) #we cant send 2d array in it as series is 1d itself

0    15
1    16
2    17
dtype: int64

In [ ]:
pd.Series(dic)

1    10
2    20
3    30
dtype: int64

In [ ]:
#DATA FRAME
# combination of multiple series is known as data frame

In [ ]:
#Creation of data frame
data = {
    'Name':['John', 'Anna', 'Peter' ,'Linda'],
    'Location':['New York', 'Paris', 'Berlin', 'London'],
    'Age':[24,13,53,33],
    'Salary': [65000,70000,62000,85000]
}

In [ ]:
df=pd.DataFrame(data)
df

    Name  Location  Age  Salary
0   John  New York   24   65000
1   Anna     Paris   13   70000
2  Peter    Berlin   53   62000
3  Linda    London   33   85000

In [ ]:
data_list = [
    ['John', 'New York', 24, 65000],
    ['Anna', 'Paris', 13, 70000],
    ['Peter', 'Berlin', 53, 62000],
    ['Linda', 'London', 33, 85000]
]

columns = ['Name', 'Location', 'Age', 'Salary']

df2 = pd.DataFrame(data_list, columns=columns)

In [ ]:
df2

    Name  Location  Age  Salary
0   John  New York   24   65000
1   Anna     Paris   13   70000
2  Peter    Berlin   53   62000
3  Linda    London   33   85000

In [ ]:
#selection and indexing of columns
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [ ]:
df2[['Age','Name']]

   Age   Name
0   24   John
1   13   Anna
2   53  Peter
3   33  Linda

In [ ]:
#Creation of new col
df2['Designation']=['doctor','eng','eng','eng']
df2

    Name  Location  Age  Salary Designation
0   John  New York   24   65000      doctor
1   Anna     Paris   13   70000         eng
2  Peter    Berlin   53   62000         eng
3  Linda    London   33   85000         eng

In [ ]:
#remove a col
df2.drop('Age',axis=1)

    Name  Location  Salary Designation
0   John  New York   65000      doctor
1   Anna     Paris   70000         eng
2  Peter    Berlin   62000         eng
3  Linda    London   85000         eng

In [ ]:
#very imp note axis=1 is used for cols and axis=0 is used for rows
df2

    Name  Location  Age  Salary Designation
0   John  New York   24   65000      doctor
1   Anna     Paris   13   70000         eng
2  Peter    Berlin   53   62000         eng
3  Linda    London   33   85000         eng

In [ ]:
#To actually delete col and row from table we use "inplace=True"
df2.drop('Designation', axis=1 , inplace=True)
df2

    Name  Location  Age  Salary
0   John  New York   24   65000
1   Anna     Paris   13   70000
2  Peter    Berlin   53   62000
3  Linda    London   33   85000

In [ ]:
#now droping the rows
df2.drop(0,axis=0)

    Name Location  Age  Salary
1   Anna    Paris   13   70000
2  Peter   Berlin   53   62000
3  Linda   London   33   85000

In [ ]:
#Selection of rows
df2.loc[0]

Name            John
Location    New York
Age               24
Salary         65000
Name: 0, dtype: object

In [ ]:
df2.loc[[0,1]]

   Name  Location  Age  Salary
0  John  New York   24   65000
1  Anna     Paris   13   70000

In [ ]:
df2.iloc[0]

Name            John
Location    New York
Age               24
Salary         65000
Name: 0, dtype: object

In [ ]:
#Selecting subsets of rows and col
df2.loc[[0,1]][["Location","Salary"]]

   Location  Salary
0  New York   65000
1     Paris   70000

In [ ]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   53
3  Linda   33

In [ ]:
#Conditional Selection
df2[df2["Age"]>30]

    Name Location  Age  Salary
2  Peter   Berlin   53   62000
3  Linda   London   33   85000

In [ ]:
df2[(df2['Age']>30) & (df2['Location']=='Berlin')]

    Name Location  Age  Salary
2  Peter   Berlin   53   62000

In [ ]:
#HANDLING MISSING DATA

In [ ]:
data = {
    'A' : [1,2,np.nan,4,5],
    'B' : [1,2,3,4,5],
    'C' : [1,2,3,np.nan,np.nan],
    'D' : [1,np.nan,np.nan,np.nan,5]
} #np.na are null values
df3=pd.DataFrame(data)
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
#Finding Missing Data
df3.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df3.isna().sum()#it counted how many null values are in columns

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
df3.isna().any() #means each col has null values

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
#Removing NUll Values or Missing Data
#it works on row basis
df3.dropna() # all the values in row are droped where they have null values except
#the second row

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df3.dropna(thresh=3) #thresh is like a limit means
#remove rows except which has 3 non null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
#Filling The Missing Data

In [ ]:
#filling null values with 0
df3.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
#filling missing data with different values in each col
values={'A':0,'B':100,'C':200,'D':300}
df3.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  300.0
2  0.0  3    3.0  300.0
3  4.0  4  200.0  300.0
4  5.0  5  200.0    5.0

In [ ]:
#filling values with mean
df3.fillna(df3.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0