In [ ]:
#PANDAS

In [ ]:
#MERGING, JOINING AND CONCATINATION

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['bob','jake','lisa','sue','peter'],
    'department':['accounting','engineering','engineering','hr','IT']})

#Data frame 2: Salary Information
salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[70000,80000,60000,90000,100000],
    'bonus':[5000,10000,7000,8000,12000]})

In [ ]:
employees

   employee_id   name   department
0            1    bob   accounting
1            2   jake  engineering
2            3   lisa  engineering
3            4    sue           hr
4            5  peter           IT

In [ ]:
salaries

   employee_id  salary  bonus
0            1   70000   5000
1            2   80000  10000
2            3   60000   7000
3            6   90000   8000
4            7  100000  12000

In [ ]:
pd.merge(employees,salaries,how='inner',on='employee_id')#how ="inner" means will merge common parts from both the tables

   employee_id  name   department  salary  bonus
0            1   bob   accounting   70000   5000
1            2  jake  engineering   80000  10000
2            3  lisa  engineering   60000   7000

In [ ]:
# how="outer" means will merge on the basis of column or employee id
pd.merge(employees,salaries,how='outer',on='employee_id')

   employee_id   name   department    salary    bonus
0            1    bob   accounting   70000.0   5000.0
1            2   jake  engineering   80000.0  10000.0
2            3   lisa  engineering   60000.0   7000.0
3            4    sue           hr       NaN      NaN
4            5  peter           IT       NaN      NaN
5            6    NaN          NaN   90000.0   8000.0
6            7    NaN          NaN  100000.0  12000.0

In [ ]:
pd.merge(employees,salaries,how='left',on='employee_id')#merging based on emp id

   employee_id   name   department   salary    bonus
0            1    bob   accounting  70000.0   5000.0
1            2   jake  engineering  80000.0  10000.0
2            3   lisa  engineering  60000.0   7000.0
3            4    sue           hr      NaN      NaN
4            5  peter           IT      NaN      NaN

In [ ]:
pd.merge(employees,salaries,how='right',on='employee_id')#merging based on salaries

   employee_id  name   department  salary  bonus
0            1   bob   accounting   70000   5000
1            2  jake  engineering   80000  10000
2            3  lisa  engineering   60000   7000
3            6   NaN          NaN   90000   8000
4            7   NaN          NaN  100000  12000

In [ ]:
#CONCATINATION OF 2 DATAFRAMES
df1=pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3']
})

df2=pd.DataFrame({
    'A':['A4','A5','A6','A7'],
    'B':['B4','B5','B6','B7'],
    'C':['C4','C5','C6','C7']
})

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [ ]:
df2

    A   B   C
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7

In [ ]:
pd.concat([df1,df2]) #based on cols

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7

In [ ]:
pd.concat([df1,df2],axis=1)#based on rows

    A   B   C   A   B   C
0  A0  B0  C0  A4  B4  C4
1  A1  B1  C1  A5  B5  C5
2  A2  B2  C2  A6  B6  C6
3  A3  B3  C3  A7  B7  C7

In [ ]:
# JOINING DATAFRAMES
df1=pd.DataFrame({
    'name':['bob','jake','lisa','sue'],
    'index':[1,2,3,4]
})

df2=pd.DataFrame({
    'score':[70,80,60,90],
    'index':[2,3,4,5]
})

In [ ]:
df1

   name  index
0   bob      1
1  jake      2
2  lisa      3
3   sue      4

In [ ]:
df2

   score  index
0     70      2
1     80      3
2     60      4
3     90      5

In [ ]:
df1.join(df2,how='outer',lsuffix='_left',rsuffix='_right')

   name  index_left  score  index_right
0   bob           1     70            2
1  jake           2     80            3
2  lisa           3     60            4
3   sue           4     90            5

In [ ]:
#GROUP BY AGGREGATION

In [ ]:
data = {
    'Category':['A','A','B','B','A','B', 'A' , 'B'],
    'Stores':['Store1','Store2','Store1','Store2','Store1','Store2','Store1', 'Store2'],
    'Sales':[100,150,200,250,300,350,120,180],
    'Quantity':[5,10,15,20,25,30,35,36],
    'Date':pd.date_range('2023-01-01',periods=8)

}
df=pd.DataFrame(data)

In [ ]:
df

  Category  Stores  Sales  Quantity       Date
0        A  Store1    100         5 2023-01-01
1        A  Store2    150        10 2023-01-02
2        B  Store1    200        15 2023-01-03
3        B  Store2    250        20 2023-01-04
4        A  Store1    300        25 2023-01-05
5        B  Store2    350        30 2023-01-06
6        A  Store1    120        35 2023-01-07
7        B  Store2    180        36 2023-01-08

In [ ]:
#group by category and calculate the sum of sales
cat=df.groupby('Category')['Sales']
for i,v in cat:
    print(i)
    print(v)

A
0    100
1    150
4    300
6    120
Name: Sales, dtype: int64
B
2    200
3    250
5    350
7    180
Name: Sales, dtype: int64

In [ ]:
df.groupby('Category')['Sales'].sum()

Category
A    670
B    980
Name: Sales, dtype: int64

In [ ]:
#group by stores and calculate the sum of sales
df.groupby('Stores')['Sales'].sum()
#there ara two types of data qualitative and qunatitaive(numbers)
#we usally do group by categorical data (qualitative data)

Stores
Store1    720
Store2    930
Name: Sales, dtype: int64

In [ ]:
#group by multiple columns
#group by category and store
df.groupby(['Category','Stores'])['Sales'].sum()

Category  Stores
A         Store1    520
          Store2    150
B         Store1    200
          Store2    780
Name: Sales, dtype: int64

In [ ]:
# AGGREGATION -> it means when u are finding result by combining  multiple things
# Basic Agg fn are mean, mode , median ,Standard deviation ,etc

In [ ]:
df['Sales'].mean()

np.float64(206.25)

In [ ]:
df['Sales'].median()

190.0

In [ ]:
df['Sales'].mode()

0    100
1    120
2    150
3    180
4    200
5    250
6    300
7    350
Name: Sales, dtype: int64

In [ ]:
df['Sales'].min()

100

In [ ]:
#we have a "".agg()" fn where we can find multiple things at same time
df['Sales'].agg(['mean','median','min','max'])

mean      206.25
median    190.00
min       100.00
max       350.00
Name: Sales, dtype: float64

In [ ]:
# PIVOT TABLES

In [ ]:
data = {
    'Date':pd.date_range('2023-01-01',periods=20),
    'Product':['A','B','C','D']*5,
    'Regions':['North','South','East','West','North','South','East','West','North','South','East','West',
               'North','South','East','West','North','South','East','West'],
    'Sales':np.random.randint(100,1000,20),
    'Units':np.random.randint(10,100,20),
    'Rep':['John','Marry','Bob','Alice','John','Marry','Bob','Alice','John','Marry',
           'Bob','Alice','John','Marry','Bob','Alice','John','Marry','Bob','Alice'],
}

df=pd.DataFrame(data)
df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+df['Date'].dt.quarter.astype(str)

In [ ]:
df

         Date Product Regions  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   North    535     73   John  January      Q1
1  2023-01-02       B   South    820     98  Marry  January      Q1
2  2023-01-03       C    East    407     27    Bob  January      Q1
3  2023-01-04       D    West    610     97  Alice  January      Q1
4  2023-01-05       A   North    949     67   John  January      Q1
5  2023-01-06       B   South    514     20  Marry  January      Q1
6  2023-01-07       C    East    478     99    Bob  January      Q1
7  2023-01-08       D    West    639     74  Alice  January      Q1
8  2023-01-09       A   North    367     60   John  January      Q1
9  2023-01-10       B   South    258     49  Marry  January      Q1
10 2023-01-11       C    East    742     83    Bob  January      Q1
11 2023-01-12       D    West    350     90  Alice  January      Q1
12 2023-01-13       A   North    769     24   John  January      Q1
13 2023-01-14       B   South    215     77  Marry  January      Q1
14 2023-01-15       C    East    382     51    Bob  January      Q1
15 2023-01-16       D    West    764     75  Alice  January      Q1
16 2023-01-17       A   North    978     24   John  January      Q1
17 2023-01-18       B   South    625     51  Marry  January      Q1
18 2023-01-19       C    East    781     99    Bob  January      Q1
19 2023-01-20       D    West    427     93  Alice  January      Q1

In [ ]:
pd.pivot_table(df,index='Regions',values='Sales',columns="Product",aggfunc='median')

Product      A      B      C      D
Regions
East       NaN    NaN  478.0    NaN
North    769.0    NaN    NaN    NaN
South      NaN  514.0    NaN    NaN
West       NaN    NaN    NaN  610.0

In [ ]:
#pivot tables are used to create heat maps
pd.pivot_table(df,index='Regions',values=['Sales','Units'],columns="Product",aggfunc='median')
# note when u are using agg fn values should be numeric

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Regions
East       NaN    NaN  478.0    NaN   NaN   NaN  83.0   NaN
North    769.0    NaN    NaN    NaN  60.0   NaN   NaN   NaN
South      NaN  514.0    NaN    NaN   NaN  51.0   NaN   NaN
West       NaN    NaN    NaN  610.0   NaN   NaN   NaN  90.0

In [ ]:
# CROSS TABS ->same as pivot table but a baisc diff is there
# we use here counting functions instead of aggregation fn
pd.crosstab(df['Regions'],df['Product'])

Product  A  B  C  D
Regions
East     0  0  5  0
North    5  0  0  0
South    0  5  0  0
West     0  0  0  5

In [ ]:
# OPERATIONS

In [ ]:
# DATA FRAME BASIC OPERATIONS
df=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df.shape

(5, 3)

In [ ]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [ ]:
# DATAFRAME APPLYING FUNCTIONS

In [ ]:
def sqr(x):
  return x*2

In [ ]:
df['D']=df['B'].apply(sqr)
df

   A        B    C         D
0  1    10000  100     20000
1  2   160000  200    320000
2  3   810000  300   1620000
3  4  2560000  400   5120000
4  5  6250000  500  12500000

In [ ]:
df['D']=df['B'].apply(lambda x : x**2)

In [ ]:
df

   A        B    C               D
0  1    10000  100       100000000
1  2   160000  200     25600000000
2  3   810000  300    656100000000
3  4  2560000  400   6553600000000
4  5  6250000  500  39062500000000